{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thunderdome-planning-poker.serviceAccountName" . }}
  namespace: {{.Values.Namespace}}
  labels:
    {{- include "thunderdome-planning-poker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
